jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'codex'

    permissions:
      contents: write
      pull-requests: write
      actions: write

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      # OpenAI Platform で「Project」を有効化してキーを発行した場合は併せて設定（任意）
      OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      # ★ 古いモデル設定/保存トークンを確実に捨てる
      - name: Reset Codex local state
        shell: bash
        run: |
          codex logout || true
          rm -rf ~/.codex || true

      - name: Generate patch with Codex
        id: codex_patch
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          set -euo pipefail

          # ★ 非対話 + モデル強制 + 出力をファイル化（デバッグしやすく）
          codex exec \
            --full-auto \
            --color never \
            -c model="o4-mini" \
            --output-last-message codex-last.txt \
            "$PROMPT"

          echo "----- Codex last message (first 200 lines) -----"
          sed -n '1,200p' codex-last.txt || true
          echo "------------------------------------------------"
