name: Issue to PR with Codex

on:
  issues:
    types: [labeled]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'codex'

    permissions:
      contents: write
      pull-requests: write
      actions: write

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git user
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure required secrets are configured
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::error::OPENAI_API_KEY is not configured"; exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      # ★ ここでCLIの保存状態を必ず無効化（既定モデルの持ち越しを防ぐ）
      - name: Reset Codex local state
        shell: bash
        run: |
          codex logout || true
          rm -rf ~/.codex || true

      - name: Generate patch with Codex
        id: codex_patch
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        shell: bash
        run: |
          set -euo pipefail

          BRANCH="codex/issue-${ISSUE_NUMBER}"
          git switch -c "$BRANCH"

          PROMPT="$(printf '%s\n\n%s\n%s\n' \
            "$ISSUE_TITLE" \
            "$ISSUE_BODY" \
            "最後に \`npm ci && npm run build\` を実行してエラーが出ないことを確認してください。'.git' などドットで始まるファイル/フォルダは絶対に変更しないでください。")"

          # ★ モデルを強制、非対話、色なし、最終メッセージ保存
          codex exec \
            --full-auto \
            --color never \
            -c model="o4-mini" \
            --output-last-message codex-last.txt \
            "$PROMPT"

          echo "----- Codex banner (model should be o4-mini) -----"
          sed -n '1,12p' codex-last.txt || true
          echo "--------------------------------------------------"

          if [[ -z "$(git status --porcelain)" ]]; then
            echo "::notice::Codex did not produce any changes; skipping push and PR creation."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          git add -A
          git commit -m "Fix: #${ISSUE_NUMBER} - ${ISSUE_TITLE}"
          git push -u origin "$BRANCH"

      - name: Create Pull Request
        if: steps.codex_patch.outputs.has_changes == 'true'
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          DEFAULT_GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -euo pipefail

          BRANCH="codex/issue-${ISSUE_NUMBER}"
          TITLE="Fix: #${ISSUE_NUMBER} – ${ISSUE_TITLE}"
          BODY="Automated fix generated by Codex CLI."

          if [ -n "${PAT_TOKEN:-}" ]; then
            export GH_TOKEN="$PAT_TOKEN"
          else
            export GH_TOKEN="$DEFAULT_GITHUB_TOKEN"
          fi

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "repos/${GITHUB_REPOSITORY}/pulls" \
            -f title="$TITLE" \
            -f head="$BRANCH" \
            -f base="main" \
            -f body="$BODY" \
            >/tmp/pr-response.json

          PR_URL=$(jq -r '.html_url // empty' /tmp/pr-response.json)
          if [ -n "$PR_URL" ]; then
            echo "::notice::Pull request created: $PR_URL"
          fi
