name: Issue to PR with Codex

on:
  issues:
    types: [labeled]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'codex'

    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Generate patch with Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          BRANCH="codex/issue-${{ github.event.issue.number }}"
          git switch -c "$BRANCH"

          if [ -d "node_modules" ]; then
            rm -rf node_modules
          fi

          if [ -f "package-lock.json" ]; then
            rm package-lock.json
          fi

          PROMPT="$(printf '%s\n\n%s\n%s\n' \
            "${{ github.event.issue.title }}" \
            "${{ github.event.issue.body }}" \
            "最後に\`npm ci && npm run build\`を実行してエラーが出ないことを確認してください。 .gitのような'.'から始まるファイル、フォルダの中身は絶対に変更しないでください。"
          )"

          codex -a full-auto --quiet "$PROMPT"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Fix: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          fi

          git push -u origin "$BRANCH"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="codex/issue-${{ github.event.issue.number }}"
          gh pr create \
            --title "Fix: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}" \
            --body "Automated fix generated by Codex CLI." \
            --base main \
            --head "$BRANCH"
