name: PR summary by codex

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-summary-by-codex:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout head commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Ensure OPENAI_API_KEY is configured
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::error::OPENAI_API_KEY secret is not configured. Add it in repository settings to enable Codex summaries." >&2
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Generate summary and comment
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.number }}
        shell: bash
        run: |
          set -euo pipefail

          npm install -g @openai/codex

          # 変更差分をファイル化
          gh pr diff "$PR_NUMBER" > pr-diff.txt

          # Codexで日本語サマリを作成（ヒアドキュメントを使わず、素直に引数で渡す）
          codex exec --full-auto -m o4-mini --color never \
            --output-last-message codex-summary.md \
            "次のファイル pr-diff.txt を読み、技術的変更点を日本語でMarkdown要約してください。\n- 目的/背景（推測可）\n- 主な変更点の箇条書き（ファイル/関数/設定）\n- 破壊的変更や注意点（あれば）\n- 確認手順（lint/build/test）\n出力は1つのMarkdownとして出力し、余計な前置きは不要です。"

          # PRにコメント投稿
          gh pr comment --body-file codex-summary.md "$PR_URL"
