name: PR summary by codex

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-summary-by-codex:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout head commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Ensure OPENAI_API_KEY is configured
        run: |
          set -euo pipefail

          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::error::OPENAI_API_KEY secret is not configured. Add it in repository settings to enable Codex summaries." >&2
            exit 1
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Generate summary and comment
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          set -euo pipefail

          npm install -g @openai/codex

          gh pr diff "$PR_NUMBER" > pr-diff.txt

          PROMPT="$(cat <<'PROMPT_EOF'
プルリクエストの差分は `pr-diff.txt` に保存されています。このファイルを確認し、変更点を日本語で簡潔に要約してください。重要なポイントを箇条書きにし、必要に応じて確認事項やリスクがあれば最後に追記してください。結果は Markdown 形式で 80 文字程度を目安に改行し、最終メッセージでは要約のみを出力してください。
PROMPT_EOF
          )"

          codex exec --full-auto -m o4-mini --color never --output-last-message codex-summary.md "$PROMPT"

          gh pr comment --body-file codex-summary.md "$PR_URL"
        shell: bash
