name: PR summary by codex

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-summary-by-codex:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout head commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Generate summary and comment
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          npm install -g @openai/codex

          gh pr diff "$PR_NUMBER" > pr-diff.txt

          codex -m o4-mini -a auto-edit --quiet \
            "pr-diff.txt から更新差分を日本語で要約して。変更があったファイルの内容を確認して。プルリクエストとして要約内容をcodex-summary.md に保存して。"

          gh pr comment --body-file codex-summary.md "$PR_URL"
